// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CloseSidesTabs
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CloseSidesTabsString = "4403533d-024d-4ba4-8774-48453a86044a";
        public static Guid CloseSidesTabs = new Guid(CloseSidesTabsString);

        public const string TabsMenuString = "d309f791-903f-11d0-9efc-00a0c911004f";
        public static Guid TabsMenu = new Guid(TabsMenuString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CloseSidesTabsGroup = 0x0001;
        public const int CloseTabsToRight = 0x0100;
        public const int CloseTabsToLeft = 0x0101;
        public const int TabsRightClickMenu = 0x042B;
    }
}